# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=10)),
                ('cm', models.CharField(max_length=4)),
                ('dm_oracle', models.CharField(max_length=4)),
                ('java_formater', models.CharField(max_length=4)),
                ('java_Deai_js', models.CharField(max_length=4)),
                ('pvt', models.CharField(max_length=20)),
                ('testnap', models.CharField(max_length=20)),
                ('bre', models.CharField(max_length=20)),
                ('rre', models.CharField(max_length=20)),
                ('syc_pdc', models.CharField(max_length=20)),
            ],
        ),
    ]
